**NUmpy Modules**: **1Dimenssion Array**

In [1]:
import numpy as np

print('1D Array')

a= np.array([1, 2, 3, 4, 5])

print(a)

1D Array
[1 2 3 4 5]


**2D Array**

In [2]:
print('2D Array')
b= np.array([[1, 2, 3, 4, 5],
             [6, 7, 8, 9, 10]])
print(b)

2D Array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


**3D Array** 

In [3]:
print('3D Array')
c= np.array([[[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10],
              [11, 12, 13, 14, 15]]])
print(c)

3D Array
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]


**Size & Shape**

In [5]:
print(a.size)
print(b.size)
print(c.size)

print(a.shape)
print(b.shape)
print(c.shape)

5
10
15
(5,)
(2, 5)
(1, 3, 5)


**Transpose matrix using Numpy:**

In [8]:
matrix = np.array([[10, 15, 20],
              [25, 30, 35]])
print("Original matrix:")
print(matrix)

##for Transpose matrix
transposed= m.T
print("\n transposed matrix:")
print(transposed)


Original matrix:
[[10 15 20]
 [25 30 35]]

 transposed matrix:
[[10 25]
 [15 30]
 [20 35]]


**Addition of 2D matrix:**

In [10]:
matrix = np.array([[10, 15, 20],
              [25, 30, 35]])
print("Original Matrix:")
print(matrix)

print("\n addition matrix:")
Addition = sum(matrix)

print(Addition)


Original Matrix:
[[10 15 20]
 [25 30 35]]

 addition matrix:
[35 45 55]
