**Functions of Numpy: Ones function**

In [3]:
import numpy as np

a= np.ones(6, dtype = int)
print(a)

[1 1 1 1 1 1]


**Zeros function**

In [4]:
b= np.zeros((4,8), dtype = int)
print(b)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


**Arrange  & Reshape function**

In [16]:
a= np.arange(1,21)
print(a)

b= a.reshape((4,5))
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


**Task**

In [9]:
import numpy as np

##Arrange the array

a= np.arange(0,18)
b= np.arange(20,38)
print(a)
print(b)
print()
##Reshape the array
c= a.reshape((6,3))
d= b.reshape((6,3))
print( c)
print()
print(d)
print()
##Addition the reshape array
Addition = sum(c,d)
print(Addition)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]

[[20 21 22]
 [23 24 25]
 [26 27 28]
 [29 30 31]
 [32 33 34]
 [35 36 37]]

[[65 72 79]
 [68 75 82]
 [71 78 85]
 [74 81 88]
 [77 84 91]
 [80 87 94]]


In [13]:
import pandas as pd 
df = pd.DataFrame({'Yes':[50,21], 'No': [131,2]})
print(df)

   Yes   No
0   50  131
1   21    2
